package com.a.model.usuario;

import java.io.Serializable;

import com.a.model.EntityBase;
import javax.xml.bind.annotation.XmlRootElement;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@XmlRootElement
@JsonIgnoreProperties(ignoreUnknown=true)
public class Usuario extends EntityBase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_usuario.id
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_usuario.nombre
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_usuario
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_usuario.id
     *
     * @return the value of t_usuario.id
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_usuario.id
     *
     * @param id the value for t_usuario.id
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_usuario.nombre
     *
     * @return the value of t_usuario.nombre
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_usuario.nombre
     *
     * @param nombre the value for t_usuario.nombre
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usuario
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Usuario other = (Usuario) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usuario
     *
     * @mbggenerated Tue Jun 17 08:17:26 CEST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        return result;
    }
}
